[package]
name = "client"
version = "0.1.0"
authors = ["Dylan Visher <dvisher1@gmail.com>"]

[dependencies]
clap = { version = "2.4.3", features = ["yaml"] }
rand = "0.3"
time = "0.1.35"

[dependencies.smr]
path = "../smr"
